# Переменная версии образа
ARG VERSION = latest

FROM python:3.11-slim

# Автор образа
MAINTAINER Mr. Artem Parhomenko

# Условная верисия контейнера
LABEL version=""

# Рабочия директория внутри контейнера
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Установка библиотек
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код приложения в контейнер
COPY app.py .

# Открываем прабочий порт
EXPOSE 8000

# Команда запуска сервера
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
